/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedKleidungRouteImport } from './routes/_authenticated/kleidung'
import { Route as AuthenticatedUebersichtRouteImport } from './routes/_authenticated/uebersicht'
import { Route as AuthenticatedVerleihRouteImport } from './routes/_authenticated/verleih'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKleidungRoute = AuthenticatedKleidungRouteImport.update({
  id: '/kleidung',
  path: '/kleidung',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUebersichtRoute = AuthenticatedUebersichtRouteImport.update({
  id: '/uebersicht',
  path: '/uebersicht',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVerleihRoute = AuthenticatedVerleihRouteImport.update({
  id: '/verleih',
  path: '/verleih',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/kleidung': typeof AuthenticatedKleidungRoute
  '/uebersicht': typeof AuthenticatedUebersichtRoute
  '/verleih': typeof AuthenticatedVerleihRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/kleidung': typeof AuthenticatedKleidungRoute
  '/uebersicht': typeof AuthenticatedUebersichtRoute
  '/verleih': typeof AuthenticatedVerleihRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/kleidung': typeof AuthenticatedKleidungRoute
  '/_authenticated/uebersicht': typeof AuthenticatedUebersichtRoute
  '/_authenticated/verleih': typeof AuthenticatedVerleihRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/auth' | '/dashboard' | '/kleidung' | '/uebersicht' | '/verleih'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/dashboard' | '/kleidung' | '/uebersicht' | '/verleih'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/kleidung'
    | '/_authenticated/uebersicht'
    | '/_authenticated/verleih'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kleidung': {
      id: '/_authenticated/kleidung'
      path: '/kleidung'
      fullPath: '/kleidung'
      preLoaderRoute: typeof AuthenticatedKleidungRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/uebersicht': {
      id: '/_authenticated/uebersicht'
      path: '/uebersicht'
      fullPath: '/uebersicht'
      preLoaderRoute: typeof AuthenticatedUebersichtRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/verleih': {
      id: '/_authenticated/verleih'
      path: '/verleih'
      fullPath: '/verleih'
      preLoaderRoute: typeof AuthenticatedVerleihRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedKleidungRoute: typeof AuthenticatedKleidungRoute
  AuthenticatedUebersichtRoute: typeof AuthenticatedUebersichtRoute
  AuthenticatedVerleihRoute: typeof AuthenticatedVerleihRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedKleidungRoute: AuthenticatedKleidungRoute,
  AuthenticatedUebersichtRoute: AuthenticatedUebersichtRoute,
  AuthenticatedVerleihRoute: AuthenticatedVerleihRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
